name: nightly

on:
  push:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.5'

      - name: setup release environment
        run: |-
          echo -e "GITHUB_TOKEN=${{secrets.ACCESS_TOKEN}}" >> .release-env

      - if: github.repository == 'sakarie9/kikitoru'
        name: release publish
        run: |-
          make snapshot-dry-run

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: kikitoru
          path: dist/*

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: goreleaser
    strategy:
      matrix:
        release-version:
        - linux_amd64_v1
        - linux_amd64_v3
        - linux_arm64
        - windows_amd64
        - windows_arm64
        - darwin_amd64
        - darwin_arm64
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: kikitoru

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: kikitoru_${{ matrix.release-version }}
          path: ./*${{ matrix.release-version }}*/kikitoru*
